version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
  app:
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
      - react-app

  react-app: # Définir l'application React comme un service séparé
    build: ../REACT_CLIENT # Chemin vers votre application React relatif à la racine de votre projet
    ports:
      - '80:80' # Port sur lequel votre application React sera disponible

volumes:
  mongo-data:
